// Code generated by goctl. DO NOT EDIT.
package types

type User struct {
	Id            int64  `json:"id"`
	Name          string `json:"name"`
	FollowCount   string `json:"follow_count"`
	FollowerCount string `json:"follower_count"`
	IsFollow      bool   `json:"is_follow"`
}

type LoginReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginReply struct {
	UserId int64  `json:"user_id"`
	Name   string `json:"name"`
	Token  string `json:"token"`
}

type RegisterReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type RegisterReply struct {
	UserId int64  `json:"user_id"`
	Token  string `json:"token"`
}

type UserInfoReq struct {
	UserId int64  `json:"user_id"`
	Token  string `json:"token"`
}

type UserInfoReply struct {
	UserInfo User `json:"user"`
}
